/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "UrlShortenerApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "UrlShortenerApiAuthEnabled": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UrlShortenerApiAuthKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UrlShortenerOpenApiDocsEnabled": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UrlShortenerRedirectHandlerFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "UrlShortenerRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "UrlShortenerShortIdLength": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UrlShortenerTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
