/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "WebhookServiceApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "WebhookServiceApiAuthEnabled": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WebhookServiceApiAuthKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WebhookServiceOpenApiDocsEnabled": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WebhookServiceRedirectHandlerFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "WebhookServiceRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "WebhookServiceShortIdLength": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WebhookServiceTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
